apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: todolist
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: camilas.dev@gmail.com
  lifecycle: experimental
  definition: https://petstore.swagger.io/v2/swagger.json
